[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mysqli', 'php82Extensions.mbstring', 'php82Extensions.curl', 'php82Extensions.gd']

[phases.build]
cmds = ['echo "Build phase complete"']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'
